name: 自动上传京东互助码
on:
  schedule:
    - cron: '10 18 1,10,20 * *'
  workflow_dispatch:
jobs:
  jdJob:
    runs-on: ubuntu-latest
    steps:
      - name: "京东农场互助码上传"
        run: |
          MyFruit1Code1=0; \
          while (($MyFruit1Code1 != 400)); \
          do \
            code=`curl http://api.turinglabs.net/api/v1/jd/farm/create/${{ secrets.MyFruit1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "MyFruit1Code1="$MyFruit1Code1; \
          done;
          MyFruit1Code2=0; \
          while (($MyFruit1Code2 != 400)); \
          do \
            code=`curl http://api.turinglabs.net/api/v1/jd/farm/create/${{ secrets.MyFruit2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "MyFruit2Code2="$MyFruit2Code2; \
          done;
      - name: "种豆得豆互助码上传"
        run: |
          export MyBean1Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/bean/create/${{ secrets.MyBean1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyBean2Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/bean/create/${{ secrets.MyBean2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: "东东萌宠互助码上传"
        run: |
          export MyPet1Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/pet/create/${{ secrets.MyPet1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyPet2Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/pet/create/${{ secrets.MyPet2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: "京喜工厂互助码上传"
        run: |
          export MyDreamFactory1Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/jxfactory/create/${{ secrets.MyDreamFactory1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyDreamFactory2Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/jxfactory/create/${{ secrets.MyDreamFactory2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: "东东工厂互助码上传"
        run: |
          export MyJdFactory1Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/ddfactory/create/${{ secrets.MyJdFactory1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyJdFactory2Res=`curl -X GET http://api.turinglabs.net/api/v1/jd/ddfactory/create/${{ secrets.MyJdFactory2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: "京东赚赚互助码上传"
        run: |
          export MyJdzz1Res=`curl -X GET https://code.chiang.fun/api/v1/jd/jdzz/create/${{ secrets.MyJdzz1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyJdzz2Res=`curl -X GET https://code.chiang.fun/api/v1/jd/jdzz/create/${{ secrets.MyJdzz2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: "疯狂的Joy互助码上传"
        run: |
          export MyJoy1Res=`curl -X GET https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/${{ secrets.MyJoy1 }}/ | grep -Po '(?<=code":)[0-9]+'`
          export MyJoy2Res=`curl -X GET https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/${{ secrets.MyJoy2 }}/ | grep -Po '(?<=code":)[0-9]+'`
      - name: Notify To Telegram
        run: |
          echo $MyFruit1Res
#          curl -s -o /dev/null -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
#          -H "Content-Type: application/json" \
#          --data '{"text": "${{github.workflow}}完成","chat_id": "${{ secrets.TG_USER_ID }}"}'
